apiVersion: v1
kind: PersistentVolume
metadata:
  name: portfolio-pv
  namespace: devops
  labels:
    type: local
    app: portfolio
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/danny/Documents/Git/kube-portfolio/portfolio" # Use this as a submodule path for permanence ##TODO: change to Azure Storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: devops
  name: portfolio-pvc
  labels:
    app: portfolio
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: hostpath
  volumeName: portfolio-pv # Bind to the created PV
  accessModes:
    - ReadWriteOnce
  selector:
    matchExpressions:
      - key: type
        operator: In
        values:
          - local