apiVersion: v1
kind: Service
metadata:
  name: portfolio-svc
  namespace: portfolio
  labels:
    app: portfolio
spec:
  selector:
    app: portfolio
  type: LoadBalancer  # Use LoadBalancer for cloud environments; use NodePort for local clusters
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http